CREATE TABLE it_company_department (
                                       department_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       department_location_city VARCHAR(15) NOT NULL,
                                       department_address VARCHAR(50) NOT NULL,
                                       department_phone_number VARCHAR(20) NOT NULL,
                                       department_email VARCHAR(50) NOT NULL
);

CREATE TABLE developer_team (
                                team_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                department_id integer REFERENCES it_company_department (department_id),
                                team_name VARCHAR(50) NOT NULL UNIQUE,
                                team_foundation_date DATE NOT NULL
);

CREATE TABLE client (
                        client_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        department_id integer REFERENCES it_company_department (department_id),
                        client_name VARCHAR(255) NOT NULL,
                        client_start_cooperation_date DATE NOT NULL
);

CREATE TABLE client_details (
                                client_id integer PRIMARY KEY REFERENCES client (client_id) ON DELETE CASCADE ON UPDATE CASCADE,
                                client_email VARCHAR(50) NOT NULL,
                                client_phone_number VARCHAR(20) NOT NULL,
                                client_budget NUMERIC NOT NULL CHECK (client_budget > 0)
);

CREATE TABLE developer(
                          developer_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          team_id integer REFERENCES developer_team (team_id),
                          developer_employment_date DATE NOT NULL,
                          developer_occupation VARCHAR(50) NOT NULL DEFAULT 'backend',
                          developer_role VARCHAR(20) NOT NULL DEFAULT 'junior'
);

CREATE TABLE developer_details (
                                   developer_id integer PRIMARY KEY REFERENCES developer (developer_id) ON DELETE CASCADE ON UPDATE CASCADE,
                                   developer_firstname VARCHAR(20) NOT NULL,
                                   developer_lastname VARCHAR(20) NOT NULL,
                                   developer_email VARCHAR(50) NOT NULL,
                                   developer_phone_number VARCHAR(20) NOT NULL,
                                   developer_salary integer NOT NULL DEFAULT 100000 CHECK (developer_salary > 0)
);

CREATE TABLE developer_performance_review (
                                              developer_id integer PRIMARY KEY REFERENCES developer (developer_id) ON DELETE CASCADE ON UPDATE CASCADE,
                                              dpr_rating numeric NOT NULL,
                                              dpr_description VARCHAR(255)
);


INSERT INTO it_company_department(department_location_city, department_address, department_phone_number, department_email)
VALUES ('Moscow', 'Lenina 34', '+78005643229', 'lenina34@mail.ru'),
       ('St. Petersburg', 'Jeleznodorozhnya 21', '+78762341290', 'spb_office@gmail.com'),
       ('Kazan', 'Abzhalilova 27', '+72344322556', 'kazan-it-office@yandex.ru'),
       ('Ufa', 'Pobedy 89', '+79987613245', 'bashkir@mail.ru'),
       ('Sochi', 'Koltsevay 77', '+79764129009', 'sochi@bing.com');


INSERT INTO developer_team(department_id, team_name, team_foundation_date)
VALUES (1, 'moscowTeam1', '2020-11-05'),
       (1, 'moscowTeam2', '2020-05-07'),
       (2, 'PetersburgTeam1', '2022-02-24'),
       (2, 'PetersburgTeam2', '2021-12-15'),
       (2, 'PetersburgTeam3', '2022-08-07'),
       (3, 'KazanTeam1', '2022-03-05'),
       (3, 'KazanTeam2', '2022-01-05'),
       (4, 'UfaTeam1', '2020-07-19'),
       (4, 'UfaTeam2', '2020-04-17'),
       (4, 'UfaTeam3', '2020-01-13'),
       (5, 'SochiTeam1', '2021-12-11'),
       (5, 'SochiTeam2', '2021-11-13');

INSERT INTO developer(team_id, developer_employment_date, developer_occupation, developer_role)
VALUES
    (1, '2020-11-14', 'frontend', 'middle'),
    (1, '2020-11-08', 'backend', 'senior'),
    (1, '2020-11-05', 'devops', 'junior'),

    (2, '2020-05-15', 'architect', 'lead'),
    (2, '2020-05-07', 'analyst', 'middle'),
    (2, '2020-05-17', 'pentest', 'middle'),

    (3, '2022-02-24', 'backend', 'junior'),
    (3, '2022-02-27', 'backend', 'junior'),
    (3, '2022-03-11', 'frontend', 'intern'),

    (4, '2021-12-15', 'frontend', 'lead'),
    (4, '2021-12-16', 'system analyst', 'junior'),
    (4, '2021-12-19', 'web design', 'senior'),

    (5, '2022-08-07', 'devops', 'junior'),
    (5, '2022-08-27', 'devops', 'junior'),
    (5, '2022-08-09', 'pentest', 'intern'),

    (6, '2022-03-05', 'backend', 'senior'),
    (6, '2022-03-08', 'frontend', 'senior'),
    (6, '2022-03-18', 'frontend', 'intern'),

    (7, '2022-01-05', 'frontend', 'senior'),
    (7, '2022-01-16', 'system analyst', 'senior'),
    (7, '2022-01-23', 'web design', 'lead'),

    (8, '2020-07-19', 'pentest', 'junior'),
    (8, '2020-07-21', 'business analyst', 'junior'),
    (8, '2020-07-19', 'pentest', 'senior'),

    (9, '2020-04-17', 'backend', 'senior'),
    (9, '2020-04-23', 'backend', 'middle'),
    (9, '2022-04-29', 'backend', 'senior'),

    (10, '2020-01-13', 'frontend', 'intern'),
    (10, '2020-01-17', 'frontend', 'intern'),
    (10, '2020-01-22', 'frontend', 'intern'),

    (11, '2021-12-15', 'web design', 'senior'),
    (11, '2021-12-16', 'system analyst', 'senior'),
    (11, '2021-12-23', 'web design', 'lead'),

    (12, '2021-11-13', 'frontend', 'senior'),
    (12, '2021-11-19', 'backend', 'lead'),
    (12, '2021-11-17', 'pentest', 'senior');


INSERT INTO developer_details(developer_id, developer_firstname, developer_lastname, developer_email, developer_phone_number, developer_salary)
VALUES
    (1, 'Egor', 'Pankratov', 'egor123@mail.ru', '+78765679089', 125600),
    (2, 'Igor', 'Melezov', 'igorrr@mail.ru', '+78909075634', 234800),
    (3, 'Vauzh', 'Maturov', 'maturga@gmail.com', '+79345671890', 65000),
    (4, 'Ilya', 'Eugenov', 'ilya111@yandex.ru', '+79112223344', 167800),
    (5, 'Artur', 'Pirozhkov', 'artur1222@mail.ru', '+79087865445', 80900),
    (6, 'Eugene', 'Patrikov', 'eugene@mail.ru', '+79432213216', 90800),

    (7, 'Vagiz', 'Hamitov', 'vag@mail.ru', '+79876787656', 43578),
    (8, 'Darya', 'Kirova', 'dashka@mail.ru', '+79078078078', 176543),
    (9, 'Maria', 'Kravetz', 'maska@gmail.com', '+79422341098', 98562),
    (10, 'Pavel', 'Alexandrov', 'pashka@yandex.ru', '+79721034089', 136790),
    (11, 'Karina', 'Ryabova', 'karinka@mail.ru', '+79566547890', 309103),
    (12, 'Pankrat', 'Matarov', 'pankrat@mail.ru', '+794522332260', 45310),

    (13, 'Alexander', 'Ovechkin', 'ovechkin123@mail.ru', '+79567689002', 339021),
    (14, 'Polina', 'Grishova', 'polka@mail.ru', '+79755479289', 125600),
    (15, 'Cristiano', 'Ronaldo', 'cr7@gmail.com', '+79765670001', 340000),
    (16, 'Marat', 'Svetov', 'maratich@mail.ru', '+79765676701', 97000),
    (17, 'Sveta', 'Teryanova', 'svetik@mail.ru', '+79765679999', 78912),
    (18, 'Ilnaz', 'Kirasov', 'ilnazka123@mail.ru', '+79765670007', 87621),


    (19, 'Pavel', 'Mashkov', 'ika@mail.ru', '+78765672334', 129000),
    (20, 'Eduard', 'Ortega', 'edik@mail.ru', '+78909079861', 200000),
    (21, 'Maksim', 'Makitov', 'maks@gmail.com', '+79345673421', 35100),
    (22, 'Anastasiya', 'Mirova', 'nastya@yandex.ru', '+79112227777', 200000),
    (23, 'Zarina', 'Ilnazova', 'zarka@mail.ru', '+79087860003', 409876),
    (24, 'Maria', 'Zavarzina', 'zavarzina@mail.ru', '+79432210980', 234561),

    (25, 'Mihail', 'Mladshov', 'mishka@mail.ru', '+79876782310', 435780),
    (26, 'Kira', 'Yashina', 'kirka@mail.ru', '+79078074554', 145542),
    (27, 'Garik', 'Harlamov', 'harla@gmail.com', '+79422342111', 890782),
    (28, 'Pavel', 'Volya', 'volya@yandex.ru', '+79721032116', 234156),
    (29, 'Andrei', 'Kurochkin', 'andrei@mail.ru', '+79566542222', 300000),
    (30, 'Andrei', 'Bebureshvili', 'bebur@mail.ru', '+794522332345', 123456),

    (31, 'Georgiy', 'Dzhikia', 'gosha@mail.ru', '+79567685667', 290789),
    (32, 'Emilia', 'Clark', 'clark@mail.ru', '+79755472167', 250000),
    (33, 'Darina', 'Giftova', 'darina@gmail.com', '+79765673221', 67900),
    (34, 'Aleksei', 'Partuyov', 'aleksiiiii@mail.ru', '+79765672309', 108000),
    (35, 'Maria', 'Zaytseva', 'zaytseva@mail.ru', '+79765678888', 230000),
    (36, 'Karla', 'Mashina', 'karla@mail.ru', '+79765672077', 150000);

INSERT INTO developer_performance_review(developer_id, dpr_rating, dpr_description)
VALUES
    (1, 56, 'Улучшить коммуникацию'),
    (2, 23, 'Токсичный'),
    (3, 89, 'С этим человеком приятно работать'),
    (4, 78, 'Улучшить восприятие критики'),
    (5, 51, 'Улучшить понимание архитектуры'),
    (6, 99, 'Нечего улучшать'),

    (7, 53, 'Улучшить коммуникацию'),
    (8, 21, 'Токсичный'),
    (9, 91, 'С этим человеком приятно работать'),
    (10, 82, 'Улучшить восприятие критики'),
    (11, 59, 'Улучшить понимание архитектуры'),
    (12, 96, 'Нечего улучшать'),


    (13, 49, 'Улучшить коммуникацию'),
    (14, 59, 'Токсичный'),
    (15, 92, 'С этим человеком приятно работать'),
    (16, 71, 'Улучшить восприятие критики'),
    (17, 58, 'Улучшить понимание архитектуры'),
    (18, 93, 'Нечего улучшать'),


    (19, 47, 'Улучшить коммуникацию'),
    (20, 57, 'Токсичный'),
    (21, 90, 'С этим человеком приятно работать'),
    (22, 69, 'Улучшить восприятие критики'),
    (23, 56, 'Улучшить понимание архитектуры'),
    (24, 91, 'Нечего улучшать'),


    (25, 51, 'Улучшить коммуникацию'),
    (26, 61, 'Токсичный'),
    (27, 94, 'С этим человеком приятно работать'),
    (28, 77, 'Улучшить восприятие критики'),
    (29, 60, 'Улучшить понимание архитектуры'),
    (30, 90, 'Нечего улучшать'),


    (31, 80, 'Улучшить коммуникацию'),
    (32, 15, 'Токсичный'),
    (33, 97, 'С этим человеком приятно работать'),
    (34, 73, 'Улучшить восприятие критики'),
    (35, 72, 'Улучшить понимание архитектуры'),
    (36, 91, 'Нечего улучшать');

INSERT INTO client(department_id, client_name, client_start_cooperation_date)
VALUES
    (1, 'OOO НЕФТЬ И ГАЗ', '2020-12-07'),
    (1, 'OOO Вася и Петя', '2020-08-15'),
    (1, 'OOO Айти борода', '2020-07-16'),
    (2, 'OOO Фрукты и Овощи', '2022-02-28'),
    (2, 'OOO Автодетали', '2021-12-19'),
    (2, 'OOO Стройка', '2021-12-29'),
    (3, 'OOO Отели', '2022-08-16'),
    (3, 'OOO Учеба', '2022-03-15'),
    (4, 'OOO Плаза', '2022-03-14'),
    (4, 'OOO Газовщики', '2021-11-29'),
    (4, 'OOO Доставка', '2020-07-30'),
    (4, 'OOO Суши и Роллы', '2020-08-27'),
    (4, 'OOO Пицца', '2020-05-04'),
    (4, 'OOO Бистро', '2020-01-29'),
    (5, 'OOO Ресторан', '2020-02-14'),
    (5, 'OOO Петя и его друзья', '2021-12-13'),
    (5, 'OOO Светильники', '2021-11-17'),
    (5, 'OOO Зум', '2021-11-18');

INSERT INTO client_details(client_id, client_email, client_phone_number, client_budget)
VALUES
    (1, 'silnya-neft@mail.ru', '+78005000567', 10609000),
    (2, 'vasekpetek@mail.ru', '+78001001010', 97600000),
    (3, 'borodaaa@mail.ru', '+78007659000', 29017390),
    (4, 'frukti@mail.ru', '+78002000000', 15000000),
    (5, 'autodetails@mail.ru', '+78007770000', 50000000),
    (6, 'stroika@mail.ru', '+78005551221', 5000000),

    (7, 'hotels@mail.ru', '+78002222211', 13456000),
    (8, 'education@mail.ru', '+78002455637', 456000),
    (9, 'plaza@mail.ru', '+78003334455', 28900000),
    (10, 'gazovschiki@mail.ru', '+78000003333', 130000),
    (11, 'delivery@mail.ru', '+7800321123', 9000000),
    (12, 'sushiirolli@mail.ru', '+78002211290', 435100),

    (13, 'pizza@mail.ru', '+78005009999', 3098909),
    (14, 'bistro@mail.ru', '+78002344334', 800000),
    (15, 'restaurant@mail.ru', '+78005000567', 10609000),
    (16, 'petyaandfriends@mail.ru', '+7800786564', 3214000),
    (17, 'dabydetsvet@mail.ru', '+78001221221', 200000),
    (18, 'zoom@mail.ru', '+78001119977', 9878901);